// Game Data
const RECYCLE_GAME_DATA_STORE = 'RECYCLE_GAME_DATA_STORE';
const FETCH_GAME_DATA = 'FETCH_GAME_DATA';
const UPDATE_GAME_DATA = 'UPDATE_GAME_DATA';

const FETCH_ALL_TEAMS = 'FETCH_ALL_TEAMS';
const UPDATE_ALL_TEAMS = 'UPDATE_ALL_TEAMS';
const RECYCLE_TEAM_STORE = 'RECYCLE_TEAM_STORE';

export {
  RECYCLE_GAME_DATA_STORE,
  FETCH_GAME_DATA,
  UPDATE_GAME_DATA,
  FETCH_ALL_TEAMS,
  UPDATE_ALL_TEAMS,
  RECYCLE_TEAM_STORE,
};

export default {
  RECYCLE_GAME_DATA_STORE,
  FETCH_GAME_DATA,
  UPDATE_GAME_DATA,
  FETCH_ALL_TEAMS,
  UPDATE_ALL_TEAMS,
  RECYCLE_TEAM_STORE,
};
