// Game Data
const RECYCLE_GAME_DATA_STORE = 'RECYCLE_GAME_DATA_STORE';
const FETCH_GAME_DATA = 'FETCH_GAME_DATA';
const UPDATE_GAME_DATA = 'UPDATE_GAME_DATA';

export {
  RECYCLE_GAME_DATA_STORE,
  FETCH_GAME_DATA,
  UPDATE_GAME_DATA
};

export default {
  RECYCLE_GAME_DATA_STORE,
  FETCH_GAME_DATA,
  UPDATE_GAME_DATA
}